# Generated by Django 2.2 on 2021-05-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20210529_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='status',
            field=models.CharField(choices=[('all', 'Публичный'), ('private', 'Приватный')], default='all', max_length=15, verbose_name='Публичный'),
        ),
    ]
